openapi: 3.0.1
info:
  title: OData Service for namespace microsoft.graph
  description: This OData service is located at https://graph.microsoft.com/beta
  version: 1.0.1
servers:
- url: https://graph.microsoft.com/beta
paths:
  "/directoryObjects/{id}/microsoft.graph.restore":
    post:
      tags:
      - directoryObjects
      summary: Invoke action restore
      operationId: Invokerestore
      parameters:
      - name: id
        in: path
        description: 'key: id'
        required: true
        schema:
          type: string
      requestBody:
        description: Action parameters
        content:
          application/json:
            schema:
              type: object
              properties:
                groupIds:
                  type: array
                  items:
                    type: string
                securityEnabledOnly:
                  type: boolean
                  default: false
                  nullable: true
          application/json2:
            schema:
              $ref: '#/components/schemas/microsoft.graph.directoryObject'
        required: true
      responses:
        '204':
          description: Success
        default:
          "$ref": "#/components/responses/error"
components:
  schemas:
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
    microsoft.graph.extension:
      allOf:
      - "$ref": "#/components/schemas/microsoft.graph.entity"
      - title: extension
        type: object
    microsoft.graph.geoCoordinates:
      title: geoCoordinates
      type: object
      properties:
        altitude:
          oneOf:
            - type: number
            - type: string
            - enum:
                - '-INF'
                - INF
                - NaN
          format: double
          nullable: true
        latitude:
          oneOf:
            - type: number
            - type: string
            - enum:
                - '-INF'
                - INF
                - NaN
          format: double
          nullable: true
        longitude:
          oneOf:
            - type: number
            - type: string
            - enum:
                - '-INF'
                - INF
                - NaN
          format: double
          nullable: true
    microsoft.graph.directoryObject:
      allOf:
      - "$ref": "#/components/schemas/microsoft.graph.entity"
      - "$ref": "#/components/schemas/microsoft.graph.geoCoordinates"
      - title: directoryObject
        type: object
        properties:
          deletedDateTime:
            pattern: "^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$"
            type: string
            format: date-time
            nullable: true
    microsoft.graph.schemaExtension:
      allOf:
      - "$ref": "#/components/schemas/microsoft.graph.entity"
      - title: schemaExtension
        type: object
        properties:
          description:
            type: string
            nullable: true
          targetTypes:
            type: array
            items:
              type: string
          properties:
            type: array
            items:
              "$ref": "#/components/schemas/microsoft.graph.extensionSchemaProperty"
          status:
            type: string
          owner:
            type: string
      example:
        id: String (identifier)
        deletedDateTime: DateTimeOffset (timestamp)
        accountEnabled: true
        assignedLicenses:
        - "@odata.type": microsoft.graph.assignedLicense
        assignedPlans:
        - "@odata.type": microsoft.graph.assignedPlan
        businessPhones:
        - String
        city: String
        companyName: String
        country: String
        department: String
        deviceKeys:
        - "@odata.type": microsoft.graph.deviceKey
        displayName: String
        employeeId: String
        givenName: String
        imAddresses:
        - String
        jobTitle: String
        mail: String
        mailNickname: String
        mobilePhone: String
        onPremisesImmutableId: String
        onPremisesLastSyncDateTime: DateTimeOffset (timestamp)
        onPremisesProvisioningErrors:
        - "@odata.type": microsoft.graph.onPremisesProvisioningError
        onPremisesSecurityIdentifier: String
        onPremisesSyncEnabled: true
        onPremisesDomainName: String
        onPremisesSamAccountName: String
        onPremisesUserPrincipalName: String
        passwordPolicies: String
        passwordProfile:
          "@odata.type": microsoft.graph.passwordProfile
        officeLocation: String
        postalCode: String
        preferredDataLocation: String
        preferredLanguage: String
        provisionedPlans:
        - "@odata.type": microsoft.graph.provisionedPlan
        proxyAddresses:
        - String
        refreshTokensValidFromDateTime: DateTimeOffset (timestamp)
        showInAddressList: true
        state: String
        streetAddress: String
        surname: String
        usageLocation: String
        userPrincipalName: String
        userType: String
        mailboxSettings:
          "@odata.type": microsoft.graph.mailboxSettings
        aboutMe: String
        birthday: DateTimeOffset (timestamp)
        hireDate: DateTimeOffset (timestamp)
        interests:
        - String
        mySite: String
        pastProjects:
        - String
        preferredName: String
        responsibilities:
        - String
        schools:
        - String
        skills:
        - String
        identityUserRisk:
          "@odata.type": microsoft.graph.identityUserRisk
        deviceEnrollmentLimit: Int32
        extensions:
        - "@odata.type": microsoft.graph.extension
        ownedDevices:
        - "@odata.type": microsoft.graph.directoryObject
        registeredDevices:
        - "@odata.type": microsoft.graph.directoryObject
        manager:
          "@odata.type": microsoft.graph.directoryObject
        directReports:
        - "@odata.type": microsoft.graph.directoryObject
        memberOf:
        - "@odata.type": microsoft.graph.directoryObject
        createdObjects:
        - "@odata.type": microsoft.graph.directoryObject
        ownedObjects:
        - "@odata.type": microsoft.graph.directoryObject
        scopedRoleMemberOf:
        - "@odata.type": microsoft.graph.scopedRoleMembership
        licenseDetails:
        - "@odata.type": microsoft.graph.licenseDetails
        activities:
        - "@odata.type": microsoft.graph.activity
        outlook:
          "@odata.type": microsoft.graph.outlookUser
        messages:
        - "@odata.type": microsoft.graph.message
        joinedGroups:
        - "@odata.type": microsoft.graph.group
        mailFolders:
        - "@odata.type": microsoft.graph.mailFolder
        calendar:
          "@odata.type": microsoft.graph.calendar
        calendars:
        - "@odata.type": microsoft.graph.calendar
        calendarGroups:
        - "@odata.type": microsoft.graph.calendarGroup
        calendarView:
        - "@odata.type": microsoft.graph.event
        events:
        - "@odata.type": microsoft.graph.event
        people:
        - "@odata.type": microsoft.graph.person
        contacts:
        - "@odata.type": microsoft.graph.contact
        contactFolders:
        - "@odata.type": microsoft.graph.contactFolder
        inferenceClassification:
          "@odata.type": microsoft.graph.inferenceClassification
        photo:
          "@odata.type": microsoft.graph.profilePhoto
        photos:
        - "@odata.type": microsoft.graph.profilePhoto
        drive:
          "@odata.type": microsoft.graph.drive
        drives:
        - "@odata.type": microsoft.graph.drive
        insights:
          "@odata.type": microsoft.graph.officeGraphInsights
        planner:
          "@odata.type": microsoft.graph.plannerUser
        onenote:
          "@odata.type": microsoft.graph.onenote
        managedDevices:
        - "@odata.type": microsoft.graph.managedDevice
        managedAppRegistrations:
        - "@odata.type": microsoft.graph.managedAppRegistration
        devices:
        - "@odata.type": microsoft.graph.device
        joinedTeams:
        - "@odata.type": microsoft.graph.group
        deviceManagementTroubleshootingEvents:
        - "@odata.type": microsoft.graph.deviceManagementTroubleshootingEvent
    microsoft.graph.extensionSchemaProperty:
      title: extensionSchemaProperty
      type: object
      properties:
        name:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
    odata.error:
      required:
      - error
      type: object
      properties:
        error:
          "$ref": "#/components/schemas/odata.error.main"
    odata.error.main:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            "$ref": "#/components/schemas/odata.error.detail"
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/odata.error"
  parameters:
    top:
      name: "$top"
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: "$skip"
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    count:
      name: "$count"
      in: query
      description: Include count of items
      schema:
        type: boolean
    filter:
      name: "$filter"
      in: query
      description: Filter items by property values
      schema:
        type: string
    search:
      name: "$search"
      in: query
      description: Search items by search phrases
      schema:
        type: string
tags:
- name: schemaExtensions
- name: directoryObjects
